# Generated by Django 5.0.7 on 2025-01-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accident", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentreporting",
            name="toolbox_number",
            field=models.CharField(default="na", max_length=20),
        ),
    ]
