# Generated by Django 5.0.7 on 2025-01-29 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accident", "0004_accidentreporting_toolbox_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accidentreporting",
            name="toolbox_number",
        ),
    ]
